version: '3.8'

services:
  savethemovie:
    build:
      context: .
      args:
        - VITE_TMDB_API_KEY=${VITE_TMDB_API_KEY}
    container_name: savethemovie
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production